/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI.Ejecutables;

import Logico.Vehiculos.Vehiculo;
import Logico.Vehiculos.VehiculosHashMap;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class Buscarvehiculos_JDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Buscarvehiculos_JDialog.class.getName());

    private VehiculosHashMap vehiculosHashMap;
    private DefaultTableModel model;
    private int Tamano;
    
    public Buscarvehiculos_JDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //Inicializar
        model= (DefaultTableModel) tblVehiculos.getModel();
        Tamano = 0;
    }
    
    public void aumentartamano() {
        if (Tamano <= 50) {
        Tamano = Tamano + 10;
        this.setSize(this.getWidth()+Tamano, this.getHeight()+Tamano); 
        }
    }
    
    public void disminuirtamano() {
        if (Tamano >= 0) {
        this.setSize(this.getWidth()-Tamano, this.getHeight()-Tamano);    
        Tamano = Tamano - 10;
        }
    }
    
    //SETS
    public void setVehiculosHashMap(VehiculosHashMap vehiculosHashMap) {
        this.vehiculosHashMap = vehiculosHashMap;
        cargartabla();
    }
          
    public void cargartabla() {
        model.setRowCount(0); //Limpia la tabla
        for (Vehiculo Vehiculo : vehiculosHashMap.getHashmap().values()) {
            Object[] data = {Vehiculo.getPlaca(),Vehiculo.getEstado(), Vehiculo.getMarca(), Vehiculo.getModelo(), Vehiculo.getAño(), Vehiculo.getCategoria()}; 
            model.addRow(data);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVehiculos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setText("   Busca un vehiculo!");
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 30));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 50, 30));

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton2.setText("-");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 50, 30));

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        tblVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Placa", "Estado", "Marca", "Modelo", "year", "Categoria"
            }
        ));
        jScrollPane1.setViewportView(tblVehiculos);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        aumentartamano();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        disminuirtamano();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Buscarvehiculos_JDialog dialog = new Buscarvehiculos_JDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tblVehiculos;
    // End of variables declaration//GEN-END:variables
}
