/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI.Ejecutables;

import Logico.Vehiculos.Vehiculo;
import Logico.Vehiculos.VehiculosHashMap;
import Utils.UtilGuis;
import java.util.HashMap;
import javax.swing.JFrame;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ASUS
 */
public class Buscarvehiculos_JDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Buscarvehiculos_JDialog.class.getName());

    private TableRowSorter<DefaultTableModel> sorter; //Se usa para reordenar los datos de una tabla
    private RowFilter<DefaultTableModel, Object> rowFilter; //Filtro
    private VehiculosHashMap vehiculosHashMap;
    private Vehiculo vehiculo;
    private DefaultTableModel model;
    private int Tamano;
    private MainFrame mainFrame;
    
    public Buscarvehiculos_JDialog(java.awt.Frame parent, boolean modal, MainFrame mainFrame) {
        super(parent, modal);
        initComponents();
        //Inicializar
        model= (DefaultTableModel) tblVehiculos.getModel();
        sorter = new TableRowSorter<>(model);  //Es el que filtra lo escrito en el JText por atributos del objeto, Busca coincidencias
        tblVehiculos.setRowSorter(sorter);
        model= (DefaultTableModel) tblVehiculos.getModel();
        Tamano = 0;
        this.mainFrame = mainFrame;
    }

    private Buscarvehiculos_JDialog(JFrame jFrame, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    public Vehiculo getVehiculo() {
        return vehiculo;
    }
    
    public void aumentartamano() {
        if (Tamano <= 50) {
        Tamano = Tamano + 10;
        this.setSize(this.getWidth()+Tamano, this.getHeight()+Tamano); 
        }
    }
    
    public void disminuirtamano() {
        if (Tamano >= 0) {
        this.setSize(this.getWidth()-Tamano, this.getHeight()-Tamano);    
        Tamano = Tamano - 10;
        }
    }
    
    //SETS
    public void setVehiculosHashMap(VehiculosHashMap vehiculosHashMap) {
        this.vehiculosHashMap = vehiculosHashMap;
        cargartabla();
    }
          
    public void cargartabla() {
        model.setRowCount(0); //Limpia la tabla
        for (Vehiculo Vehiculo : vehiculosHashMap.getHashmap().values()) {
            Object[] data = {Vehiculo.getPlaca(),Vehiculo.getEstado(), Vehiculo.getMarca(), Vehiculo.getModelo(), Vehiculo.getAño(), Vehiculo.getCategoria()}; 
            model.addRow(data);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtFilter = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVehiculos = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtFilter.setText("   Busca un vehiculo!");
        txtFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFilterActionPerformed(evt);
            }
        });
        jPanel1.add(txtFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 30));

        tblVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Placa", "Estado", "Marca", "Modelo", "year", "Categoria"
            }
        ));
        jScrollPane1.setViewportView(tblVehiculos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 462, 260));

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/Iconos/edit_delete_mail (4).png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 230, 50));

        jButton4.setBackground(new java.awt.Color(51, 51, 51));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/Iconos/accepted_48.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 230, 50));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int row =tblVehiculos.getSelectedRow();
        if (row==-1){
            UtilGuis.showErrorMessage(this, "Debe seleccionar un Vehiculo", "Error");
            return;
        }
        String id=String.valueOf(tblVehiculos.getValueAt(row,0));
        vehiculo=vehiculosHashMap.buscar(id);
        setVisible(false);
        this.dispose(); 
        mainFrame.getEditarvehiculos_jpanel().CargarInfoVehiculos();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFilterActionPerformed
        rowFilter = RowFilter.regexFilter("(?i)" + txtFilter.getText());
        sorter.setRowFilter(rowFilter);
    }//GEN-LAST:event_txtFilterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Buscarvehiculos_JDialog dialog = new Buscarvehiculos_JDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVehiculos;
    private javax.swing.JTextField txtFilter;
    // End of variables declaration//GEN-END:variables
}
